FROM node:20-alpine

WORKDIR /app

# Skip cypress
ENV CYPRESS_INSTALL_BINARY=0

COPY package.json yarn.lock ./

RUN chown -R node:node /app \
    yarn install

COPY . .

USER node

EXPOSE 7777

CMD ["yarn", "start:dev"]
